name: testapp
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGUSER=postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    container_name: db
  app:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
    - "ConnectionStrings:Postgre=Host=db;User Id=postgres;Password=123;Database=postgres;Port=5432;Pooling=false"
    restart: unless-stopped
    container_name: app
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./TestClient/dist:/etc/dist
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on: 
      app:
        condition: service_started